image: alpine/latest
packages:
  - nodejs
  - npm
sources:
  - https://git.sr.ht/~johnridesabike/johnridesa.bike
secrets:
  - c646f54e-8b1c-45e7-ba55-d51b2e27761a
tasks:
  - deploy: |
      set +x
      . ~/.netlify_auth
      set -x
      cd johnridesa.bike
      npm ci
      npm run deploy
